BADGE_DEFINITIONS = [
    {
        "badge_id": "first_session",
        "title": "First Steps",
        "description": "Complete your first TalkCraft coaching session",
        "category": "milestone",
        "icon": "star",
        "condition": {"type": "sessions_count", "operator": ">=", "value": 1},
    },
    {
        "badge_id": "practice_makes_perfect",
        "title": "Practice Makes Perfect",
        "description": "Complete 10 coaching sessions",
        "category": "milestone",
        "icon": "trophy",
        "condition": {"type": "sessions_count", "operator": ">=", "value": 10},
    },
    {
        "badge_id": "dedicated_learner",
        "title": "Dedicated Learner",
        "description": "Complete 50 coaching sessions",
        "category": "milestone",
        "icon": "crown",
        "condition": {"type": "sessions_count", "operator": ">=", "value": 50},
    },
    {
        "badge_id": "century_club",
        "title": "Century Club",
        "description": "Complete 100 coaching sessions",
        "category": "milestone",
        "icon": "diamond",
        "condition": {"type": "sessions_count", "operator": ">=", "value": 100},
    },
    {
        "badge_id": "hour_of_power",
        "title": "Hour of Power",
        "description": "Accumulate 1 hour of practice time",
        "category": "time",
        "icon": "clock",
        "condition": {"type": "practice_minutes", "operator": ">=", "value": 60},
    },
    {
        "badge_id": "marathon",
        "title": "Communication Marathon",
        "description": "Accumulate 10 hours of practice time",
        "category": "time",
        "icon": "runner",
        "condition": {"type": "practice_minutes", "operator": ">=", "value": 600},
    },
    {
        "badge_id": "streak_3",
        "title": "Getting Consistent",
        "description": "Practice for 3 days in a row",
        "category": "streak",
        "icon": "fire",
        "condition": {"type": "streak_days", "operator": ">=", "value": 3},
    },
    {
        "badge_id": "streak_7",
        "title": "Week Warrior",
        "description": "Practice for 7 days in a row",
        "category": "streak",
        "icon": "fire",
        "condition": {"type": "streak_days", "operator": ">=", "value": 7},
    },
    {
        "badge_id": "streak_30",
        "title": "Monthly Master",
        "description": "Practice for 30 days in a row",
        "category": "streak",
        "icon": "inferno",
        "condition": {"type": "streak_days", "operator": ">=", "value": 30},
    },
    {
        "badge_id": "filler_fighter",
        "title": "Filler Fighter",
        "description": "Reduce filler word rate below 3% in a session",
        "category": "skill",
        "icon": "target",
        "condition": {"type": "filler_rate", "operator": "<=", "value": 0.03},
    },
    {
        "badge_id": "pace_setter",
        "title": "Pace Setter",
        "description": "Maintain ideal speaking pace (140-170 WPM) in a session",
        "category": "skill",
        "icon": "speed",
        "condition": {"type": "pace_ideal", "operator": ">=", "value": 1},
    },
    {
        "badge_id": "grammar_guru",
        "title": "Grammar Guru",
        "description": "Complete a session with zero grammar errors",
        "category": "skill",
        "icon": "spellcheck",
        "condition": {"type": "grammar_zero", "operator": ">=", "value": 1},
    },
    {
        "badge_id": "confidence_boost",
        "title": "Confidence Boost",
        "description": "Achieve a confidence score above 85% in a session",
        "category": "skill",
        "icon": "rocket",
        "condition": {"type": "confidence_high", "operator": ">=", "value": 0.85},
    },
    {
        "badge_id": "eye_contact_master",
        "title": "Eye Contact Master",
        "description": "Maintain above 90% eye contact in a session",
        "category": "skill",
        "icon": "eye",
        "condition": {"type": "eye_contact_high", "operator": ">=", "value": 0.9},
    },
    {
        "badge_id": "posture_perfect",
        "title": "Posture Perfect",
        "description": "Maintain above 90% posture stability in a session",
        "category": "skill",
        "icon": "body",
        "condition": {"type": "posture_high", "operator": ">=", "value": 0.9},
    },
    {
        "badge_id": "all_rounder",
        "title": "All-Rounder",
        "description": "Score above 80% in all metrics in a single session",
        "category": "excellence",
        "icon": "gem",
        "condition": {"type": "all_metrics_high", "operator": ">=", "value": 0.8},
    },
    {
        "badge_id": "improvement_streak",
        "title": "On the Up",
        "description": "Improve your score for 5 consecutive sessions",
        "category": "improvement",
        "icon": "trending_up",
        "condition": {"type": "improving_sessions", "operator": ">=", "value": 5},
    },
    {
        "badge_id": "comeback_king",
        "title": "Comeback King",
        "description": "Improve your score by 20% or more from your lowest session",
        "category": "improvement",
        "icon": "recovery",
        "condition": {"type": "big_improvement", "operator": ">=", "value": 0.2},
    },
    {
        "badge_id": "mode_explorer",
        "title": "Mode Explorer",
        "description": "Try all 5 conversation modes",
        "category": "exploration",
        "icon": "compass",
        "condition": {"type": "modes_tried", "operator": ">=", "value": 5},
    },
    {
        "badge_id": "topic_explorer",
        "title": "Topic Explorer",
        "description": "Practice across 10 different topics",
        "category": "exploration",
        "icon": "globe",
        "condition": {"type": "topics_count", "operator": ">=", "value": 10},
    },
    {
        "badge_id": "interview_ace",
        "title": "Interview Ace",
        "description": "Complete 5 interview mode sessions with above 80% score",
        "category": "mode_specific",
        "icon": "briefcase",
        "condition": {"type": "interview_excellence", "operator": ">=", "value": 5},
    },
    {
        "badge_id": "speaker_pro",
        "title": "Speaker Pro",
        "description": "Complete 5 public speaking sessions with above 80% score",
        "category": "mode_specific",
        "icon": "mic",
        "condition": {"type": "speaking_excellence", "operator": ">=", "value": 5},
    },
    {
        "badge_id": "debate_champion",
        "title": "Debate Champion",
        "description": "Complete 5 debate sessions with above 80% score",
        "category": "mode_specific",
        "icon": "gavel",
        "condition": {"type": "debate_excellence", "operator": ">=", "value": 5},
    },
    {
        "badge_id": "silver_tongue",
        "title": "Silver Tongue",
        "description": "Achieve an overall score above 90%",
        "category": "excellence",
        "icon": "award",
        "condition": {"type": "score_above_90", "operator": ">=", "value": 1},
    },
    {
        "badge_id": "platinum_communicator",
        "title": "Platinum Communicator",
        "description": "Achieve an overall score above 95%",
        "category": "excellence",
        "icon": "platinum",
        "condition": {"type": "score_above_95", "operator": ">=", "value": 1},
    },
]
